#! /bin/bash
cd $files

set -ex

apt-get update
apt-get upgrade

# remove deps
apt-get remove --purge -y $(cat deps_remove.txt | tr '\n' ' ')
# add deps
apt-get install -y --no-install-recommends $(cat deps_add.txt | tr '\n' ' ')
