#! /bin/bash

mount / -o remount,rw

# Get Ethernet mac address
IFACE=e*
read LOCALMAC </sys/class/net/$IFACE/address

# Move the sites.txt to data so it can be modified if needed
# just by mounting that drive
cp /root/sites.txt /data/sites.txt

# Set address correctly based on MAC Address
while read mac tzpi url remainder
do
    if [[ $LOCALMAC == $mac ]]; then
        TZPI=$tzpi;
    fi
done < /data/sites.txt

# Final timezone setting will be done after the image is deployed on a device
ln -sf "/usr/share/zoneinfo/${TZPI}" /etc/localtime

# We need to start ssh once before we go RO, otherwise it has problems
ssh-keygen -A

mkdir -p /data/videos
ln -sf /data/videos /var/flaskapp/web-service/static/videos

mount / -o remount,ro
