#! /bin/bash
cd $files

set -ex

# If we're patching images then var and home have moves so bind
# mount them to the right location
if [ -e /var.base ] ; then
	mount --bind /var.base /var
fi

if [ -e /home.base ] ; then
	mount --bind /home.base /home
fi

apt-get update
 
# WARNING: If you want new builds to update the kernel and all new packages
# enable the following lines. This very much may break your build.
# rpi-update
# apt-get upgrade -y

# add deps
apt-get install -y --no-install-recommends $(cat deps_add.txt | tr '\n' ' ')

# NOTE: LuaKit needs to be installed after other packages to 
# make sure things are hooked up in the right order.
apt-get install -y luakit gstreamer1.0-libav gstreamer1.0-alsa

# Copy our smartboard data generator
envsubst '${fallback_video_timeout}' < load-smartboard-data.sh > /root/load-smartboard-data.sh
chmod +x /root/load-smartboard-data.sh

echo "$smartboard_base_url" > /root/smartboard-base-url
