#! /bin/bash

mount / -o remount,rw

# Get Ethernet mac address
IFACE=e*
read LOCALMAC </sys/class/net/$IFACE/address

# resolv.conf needs to be writable, so we link the one in /var
if [ -e /etc/resolv.conf ] ; then
	rm /etc/resolv.conf
fi
touch /var/resolv.conf
ln -nsf /var/resolv.conf /etc/resolv.conf

# Move the sites.txt to data so it can be modified if needed
# just by mounting that drive
cp /root/sites.txt /uboot/sites.txt
cp /root/smartboard-base-url /uboot/smartboard-base-url.txt

# Set address correctly based on MAC Address
while read mac tzpi url remainder
do
    if [[ $LOCALMAC == $mac ]]; then
        TZPI=$tzpi;
    fi
done < /uboot/sites.txt

# Final timezone setting will be done after the image is deployed on a device
ln -sf "/usr/share/zoneinfo/${TZPI}" /etc/localtime

# We need to start ssh once before we go RO, otherwise it has problems
ssh-keygen -A

mkdir -p /data/videos
ln -snf /data/videos /var/flaskapp/web-service/static/videos

mount / -o remount,ro
